// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: audit_log.sql

package storage

import (
	"context"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

const recordAuditLog = `-- name: RecordAuditLog :exec
INSERT INTO audit_log (actor_user_id, action, target_type, target_id, metadata)
VALUES ($1, $2, $3, $4, $5)
`

type RecordAuditLogParams struct {
	ActorUserID uuid.NullUUID `json:"actor_user_id"`
	Action      string        `json:"action"`
	TargetType  pgtype.Text   `json:"target_type"`
	TargetID    pgtype.Text   `json:"target_id"`
	Metadata    []byte        `json:"metadata"`
}

func (q *Queries) RecordAuditLog(ctx context.Context, arg RecordAuditLogParams) error {
	_, err := q.db.Exec(ctx, recordAuditLog,
		arg.ActorUserID,
		arg.Action,
		arg.TargetType,
		arg.TargetID,
		arg.Metadata,
	)
	return err
}
