// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: auth_identities.sql

package storage

import (
	"context"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

const countAuthIdentitiesForUser = `-- name: CountAuthIdentitiesForUser :one
SELECT count(*)
FROM auth_identities
WHERE user_id = $1
`

func (q *Queries) CountAuthIdentitiesForUser(ctx context.Context, userID uuid.UUID) (int64, error) {
	row := q.db.QueryRow(ctx, countAuthIdentitiesForUser, userID)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const createAuthIdentity = `-- name: CreateAuthIdentity :one
INSERT INTO auth_identities (user_id, provider_type, provider_config_id, subject, email_at_link, verified)
VALUES ($1, $2, $3, $4, $5, $6)
RETURNING id, user_id, email_at_link
`

type CreateAuthIdentityParams struct {
	UserID           uuid.UUID        `json:"user_id"`
	ProviderType     AuthProviderType `json:"provider_type"`
	ProviderConfigID uuid.NullUUID    `json:"provider_config_id"`
	Subject          string           `json:"subject"`
	EmailAtLink      string           `json:"email_at_link"`
	Verified         bool             `json:"verified"`
}

type CreateAuthIdentityRow struct {
	ID          uuid.UUID `json:"id"`
	UserID      uuid.UUID `json:"user_id"`
	EmailAtLink string    `json:"email_at_link"`
}

func (q *Queries) CreateAuthIdentity(ctx context.Context, arg CreateAuthIdentityParams) (*CreateAuthIdentityRow, error) {
	row := q.db.QueryRow(ctx, createAuthIdentity,
		arg.UserID,
		arg.ProviderType,
		arg.ProviderConfigID,
		arg.Subject,
		arg.EmailAtLink,
		arg.Verified,
	)
	var i CreateAuthIdentityRow
	err := row.Scan(&i.ID, &i.UserID, &i.EmailAtLink)
	return &i, err
}

const findAuthIdentity = `-- name: FindAuthIdentity :one
SELECT id, user_id, email_at_link
FROM auth_identities
WHERE provider_type = $1
  AND provider_config_id IS NOT DISTINCT FROM $2
  AND subject = $3
`

type FindAuthIdentityParams struct {
	ProviderType     AuthProviderType `json:"provider_type"`
	ProviderConfigID uuid.NullUUID    `json:"provider_config_id"`
	Subject          string           `json:"subject"`
}

type FindAuthIdentityRow struct {
	ID          uuid.UUID `json:"id"`
	UserID      uuid.UUID `json:"user_id"`
	EmailAtLink string    `json:"email_at_link"`
}

func (q *Queries) FindAuthIdentity(ctx context.Context, arg FindAuthIdentityParams) (*FindAuthIdentityRow, error) {
	row := q.db.QueryRow(ctx, findAuthIdentity, arg.ProviderType, arg.ProviderConfigID, arg.Subject)
	var i FindAuthIdentityRow
	err := row.Scan(&i.ID, &i.UserID, &i.EmailAtLink)
	return &i, err
}

const touchAuthIdentity = `-- name: TouchAuthIdentity :exec
UPDATE auth_identities
SET last_used_at = $2
WHERE id = $1
`

type TouchAuthIdentityParams struct {
	ID         uuid.UUID          `json:"id"`
	LastUsedAt pgtype.Timestamptz `json:"last_used_at"`
}

func (q *Queries) TouchAuthIdentity(ctx context.Context, arg TouchAuthIdentityParams) error {
	_, err := q.db.Exec(ctx, touchAuthIdentity, arg.ID, arg.LastUsedAt)
	return err
}
