// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: auth_settings.sql

package storage

import (
	"context"
)

const findAuthSettings = `-- name: FindAuthSettings :one
SELECT local_auth_enabled, self_signup_enabled, require_email_confirmation_for_signup
FROM auth_settings
WHERE id
`

type FindAuthSettingsRow struct {
	LocalAuthEnabled                  bool `json:"local_auth_enabled"`
	SelfSignupEnabled                 bool `json:"self_signup_enabled"`
	RequireEmailConfirmationForSignup bool `json:"require_email_confirmation_for_signup"`
}

func (q *Queries) FindAuthSettings(ctx context.Context) (*FindAuthSettingsRow, error) {
	row := q.db.QueryRow(ctx, findAuthSettings)
	var i FindAuthSettingsRow
	err := row.Scan(&i.LocalAuthEnabled, &i.SelfSignupEnabled, &i.RequireEmailConfirmationForSignup)
	return &i, err
}
