// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: click_events.sql

package storage

import (
	"context"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

const insertClickEvent = `-- name: InsertClickEvent :one
INSERT INTO click_events (short_url_id, clicked_at, referrer_host, user_agent_raw, ip_hash, stream_id)
VALUES ($1, $2, $3, $4, $5, $6)
ON CONFLICT (clicked_at, stream_id) DO NOTHING
RETURNING id
`

type InsertClickEventParams struct {
	ShortUrlID   uuid.UUID          `json:"short_url_id"`
	ClickedAt    pgtype.Timestamptz `json:"clicked_at"`
	ReferrerHost pgtype.Text        `json:"referrer_host"`
	UserAgentRaw pgtype.Text        `json:"user_agent_raw"`
	IpHash       pgtype.Text        `json:"ip_hash"`
	StreamID     string             `json:"stream_id"`
}

func (q *Queries) InsertClickEvent(ctx context.Context, arg InsertClickEventParams) (int64, error) {
	row := q.db.QueryRow(ctx, insertClickEvent,
		arg.ShortUrlID,
		arg.ClickedAt,
		arg.ReferrerHost,
		arg.UserAgentRaw,
		arg.IpHash,
		arg.StreamID,
	)
	var id int64
	err := row.Scan(&id)
	return id, err
}

const upsertClickStatsDaily = `-- name: UpsertClickStatsDaily :exec
INSERT INTO click_stats_daily (short_url_id, date, click_count)
VALUES ($1, $2, $3)
ON CONFLICT (short_url_id, date) DO UPDATE SET click_count = click_stats_daily.click_count + EXCLUDED.click_count
`

type UpsertClickStatsDailyParams struct {
	ShortUrlID uuid.UUID   `json:"short_url_id"`
	Date       pgtype.Date `json:"date"`
	ClickCount int64       `json:"click_count"`
}

func (q *Queries) UpsertClickStatsDaily(ctx context.Context, arg UpsertClickStatsDailyParams) error {
	_, err := q.db.Exec(ctx, upsertClickStatsDaily, arg.ShortUrlID, arg.Date, arg.ClickCount)
	return err
}
