// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: domains.sql

package storage

import (
	"context"

	"github.com/google/uuid"
)

const findDefaultDomain = `-- name: FindDefaultDomain :one
SELECT id
FROM domains
WHERE is_default
`

func (q *Queries) FindDefaultDomain(ctx context.Context) (uuid.UUID, error) {
	row := q.db.QueryRow(ctx, findDefaultDomain)
	var id uuid.UUID
	err := row.Scan(&id)
	return id, err
}
