// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: idp_saml_configs.sql

package storage

import (
	"context"

	"github.com/google/uuid"
)

const countAuthIdentitiesForSAMLConfig = `-- name: CountAuthIdentitiesForSAMLConfig :one
SELECT count(*)
FROM auth_identities
WHERE provider_type = 'saml' AND provider_config_id = $1
`

func (q *Queries) CountAuthIdentitiesForSAMLConfig(ctx context.Context, providerConfigID uuid.NullUUID) (int64, error) {
	row := q.db.QueryRow(ctx, countAuthIdentitiesForSAMLConfig, providerConfigID)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const createSAMLConfig = `-- name: CreateSAMLConfig :one
INSERT INTO idp_saml_configs (name, idp_entity_id, idp_sso_url, idp_certificate, email_attribute, trusted, enabled)
VALUES ($1, $2, $3, $4, $5, $6, $7)
RETURNING id, name, idp_entity_id, idp_sso_url, idp_certificate, email_attribute, trusted, enabled
`

type CreateSAMLConfigParams struct {
	Name           string `json:"name"`
	IdpEntityID    string `json:"idp_entity_id"`
	IdpSsoUrl      string `json:"idp_sso_url"`
	IdpCertificate string `json:"idp_certificate"`
	EmailAttribute string `json:"email_attribute"`
	Trusted        bool   `json:"trusted"`
	Enabled        bool   `json:"enabled"`
}

func (q *Queries) CreateSAMLConfig(ctx context.Context, arg CreateSAMLConfigParams) (*IdpSamlConfig, error) {
	row := q.db.QueryRow(ctx, createSAMLConfig,
		arg.Name,
		arg.IdpEntityID,
		arg.IdpSsoUrl,
		arg.IdpCertificate,
		arg.EmailAttribute,
		arg.Trusted,
		arg.Enabled,
	)
	var i IdpSamlConfig
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.IdpEntityID,
		&i.IdpSsoUrl,
		&i.IdpCertificate,
		&i.EmailAttribute,
		&i.Trusted,
		&i.Enabled,
	)
	return &i, err
}

const deleteSAMLConfig = `-- name: DeleteSAMLConfig :execrows
DELETE FROM idp_saml_configs
WHERE id = $1
`

func (q *Queries) DeleteSAMLConfig(ctx context.Context, id uuid.UUID) (int64, error) {
	result, err := q.db.Exec(ctx, deleteSAMLConfig, id)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const findSAMLConfigByID = `-- name: FindSAMLConfigByID :one
SELECT id, name, idp_entity_id, idp_sso_url, idp_certificate, email_attribute, trusted, enabled
FROM idp_saml_configs
WHERE id = $1
`

func (q *Queries) FindSAMLConfigByID(ctx context.Context, id uuid.UUID) (*IdpSamlConfig, error) {
	row := q.db.QueryRow(ctx, findSAMLConfigByID, id)
	var i IdpSamlConfig
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.IdpEntityID,
		&i.IdpSsoUrl,
		&i.IdpCertificate,
		&i.EmailAttribute,
		&i.Trusted,
		&i.Enabled,
	)
	return &i, err
}

const listSAMLConfigs = `-- name: ListSAMLConfigs :many
SELECT id, name, idp_entity_id, idp_sso_url, idp_certificate, email_attribute, trusted, enabled
FROM idp_saml_configs
ORDER BY name
`

func (q *Queries) ListSAMLConfigs(ctx context.Context) ([]*IdpSamlConfig, error) {
	rows, err := q.db.Query(ctx, listSAMLConfigs)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []*IdpSamlConfig
	for rows.Next() {
		var i IdpSamlConfig
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.IdpEntityID,
			&i.IdpSsoUrl,
			&i.IdpCertificate,
			&i.EmailAttribute,
			&i.Trusted,
			&i.Enabled,
		); err != nil {
			return nil, err
		}
		items = append(items, &i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateSAMLConfig = `-- name: UpdateSAMLConfig :one
UPDATE idp_saml_configs
SET name = $2, idp_entity_id = $3, idp_sso_url = $4, idp_certificate = $5, email_attribute = $6, trusted = $7, enabled = $8
WHERE id = $1
RETURNING id, name, idp_entity_id, idp_sso_url, idp_certificate, email_attribute, trusted, enabled
`

type UpdateSAMLConfigParams struct {
	ID             uuid.UUID `json:"id"`
	Name           string    `json:"name"`
	IdpEntityID    string    `json:"idp_entity_id"`
	IdpSsoUrl      string    `json:"idp_sso_url"`
	IdpCertificate string    `json:"idp_certificate"`
	EmailAttribute string    `json:"email_attribute"`
	Trusted        bool      `json:"trusted"`
	Enabled        bool      `json:"enabled"`
}

func (q *Queries) UpdateSAMLConfig(ctx context.Context, arg UpdateSAMLConfigParams) (*IdpSamlConfig, error) {
	row := q.db.QueryRow(ctx, updateSAMLConfig,
		arg.ID,
		arg.Name,
		arg.IdpEntityID,
		arg.IdpSsoUrl,
		arg.IdpCertificate,
		arg.EmailAttribute,
		arg.Trusted,
		arg.Enabled,
	)
	var i IdpSamlConfig
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.IdpEntityID,
		&i.IdpSsoUrl,
		&i.IdpCertificate,
		&i.EmailAttribute,
		&i.Trusted,
		&i.Enabled,
	)
	return &i, err
}
