// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: idp_oidc_configs.sql

package storage

import (
	"context"

	"github.com/google/uuid"
)

const countAuthIdentitiesForOIDCConfig = `-- name: CountAuthIdentitiesForOIDCConfig :one
SELECT count(*)
FROM auth_identities
WHERE provider_type = 'oidc' AND provider_config_id = $1
`

func (q *Queries) CountAuthIdentitiesForOIDCConfig(ctx context.Context, providerConfigID uuid.NullUUID) (int64, error) {
	row := q.db.QueryRow(ctx, countAuthIdentitiesForOIDCConfig, providerConfigID)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const createOIDCConfig = `-- name: CreateOIDCConfig :one
INSERT INTO idp_oidc_configs (name, issuer, client_id, client_secret_encrypted, scopes, require_email_verified_claim, enabled)
VALUES ($1, $2, $3, $4, $5, $6, $7)
RETURNING id, name, issuer, client_id, client_secret_encrypted, scopes, require_email_verified_claim, enabled
`

type CreateOIDCConfigParams struct {
	Name                      string   `json:"name"`
	Issuer                    string   `json:"issuer"`
	ClientID                  string   `json:"client_id"`
	ClientSecretEncrypted     string   `json:"client_secret_encrypted"`
	Scopes                    []string `json:"scopes"`
	RequireEmailVerifiedClaim bool     `json:"require_email_verified_claim"`
	Enabled                   bool     `json:"enabled"`
}

func (q *Queries) CreateOIDCConfig(ctx context.Context, arg CreateOIDCConfigParams) (*IdpOidcConfig, error) {
	row := q.db.QueryRow(ctx, createOIDCConfig,
		arg.Name,
		arg.Issuer,
		arg.ClientID,
		arg.ClientSecretEncrypted,
		arg.Scopes,
		arg.RequireEmailVerifiedClaim,
		arg.Enabled,
	)
	var i IdpOidcConfig
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Issuer,
		&i.ClientID,
		&i.ClientSecretEncrypted,
		&i.Scopes,
		&i.RequireEmailVerifiedClaim,
		&i.Enabled,
	)
	return &i, err
}

const deleteOIDCConfig = `-- name: DeleteOIDCConfig :execrows
DELETE FROM idp_oidc_configs
WHERE id = $1
`

func (q *Queries) DeleteOIDCConfig(ctx context.Context, id uuid.UUID) (int64, error) {
	result, err := q.db.Exec(ctx, deleteOIDCConfig, id)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const findOIDCConfigByID = `-- name: FindOIDCConfigByID :one
SELECT id, name, issuer, client_id, client_secret_encrypted, scopes, require_email_verified_claim, enabled
FROM idp_oidc_configs
WHERE id = $1
`

func (q *Queries) FindOIDCConfigByID(ctx context.Context, id uuid.UUID) (*IdpOidcConfig, error) {
	row := q.db.QueryRow(ctx, findOIDCConfigByID, id)
	var i IdpOidcConfig
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Issuer,
		&i.ClientID,
		&i.ClientSecretEncrypted,
		&i.Scopes,
		&i.RequireEmailVerifiedClaim,
		&i.Enabled,
	)
	return &i, err
}

const listOIDCConfigs = `-- name: ListOIDCConfigs :many
SELECT id, name, issuer, client_id, client_secret_encrypted, scopes, require_email_verified_claim, enabled
FROM idp_oidc_configs
ORDER BY name
`

func (q *Queries) ListOIDCConfigs(ctx context.Context) ([]*IdpOidcConfig, error) {
	rows, err := q.db.Query(ctx, listOIDCConfigs)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []*IdpOidcConfig
	for rows.Next() {
		var i IdpOidcConfig
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.Issuer,
			&i.ClientID,
			&i.ClientSecretEncrypted,
			&i.Scopes,
			&i.RequireEmailVerifiedClaim,
			&i.Enabled,
		); err != nil {
			return nil, err
		}
		items = append(items, &i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateOIDCConfig = `-- name: UpdateOIDCConfig :one
UPDATE idp_oidc_configs
SET name = $2, issuer = $3, client_id = $4, scopes = $5, require_email_verified_claim = $6, enabled = $7
WHERE id = $1
RETURNING id, name, issuer, client_id, client_secret_encrypted, scopes, require_email_verified_claim, enabled
`

type UpdateOIDCConfigParams struct {
	ID                        uuid.UUID `json:"id"`
	Name                      string    `json:"name"`
	Issuer                    string    `json:"issuer"`
	ClientID                  string    `json:"client_id"`
	Scopes                    []string  `json:"scopes"`
	RequireEmailVerifiedClaim bool      `json:"require_email_verified_claim"`
	Enabled                   bool      `json:"enabled"`
}

func (q *Queries) UpdateOIDCConfig(ctx context.Context, arg UpdateOIDCConfigParams) (*IdpOidcConfig, error) {
	row := q.db.QueryRow(ctx, updateOIDCConfig,
		arg.ID,
		arg.Name,
		arg.Issuer,
		arg.ClientID,
		arg.Scopes,
		arg.RequireEmailVerifiedClaim,
		arg.Enabled,
	)
	var i IdpOidcConfig
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Issuer,
		&i.ClientID,
		&i.ClientSecretEncrypted,
		&i.Scopes,
		&i.RequireEmailVerifiedClaim,
		&i.Enabled,
	)
	return &i, err
}

const updateOIDCConfigWithSecret = `-- name: UpdateOIDCConfigWithSecret :one
UPDATE idp_oidc_configs
SET name = $2, issuer = $3, client_id = $4, client_secret_encrypted = $5, scopes = $6, require_email_verified_claim = $7, enabled = $8
WHERE id = $1
RETURNING id, name, issuer, client_id, client_secret_encrypted, scopes, require_email_verified_claim, enabled
`

type UpdateOIDCConfigWithSecretParams struct {
	ID                        uuid.UUID `json:"id"`
	Name                      string    `json:"name"`
	Issuer                    string    `json:"issuer"`
	ClientID                  string    `json:"client_id"`
	ClientSecretEncrypted     string    `json:"client_secret_encrypted"`
	Scopes                    []string  `json:"scopes"`
	RequireEmailVerifiedClaim bool      `json:"require_email_verified_claim"`
	Enabled                   bool      `json:"enabled"`
}

func (q *Queries) UpdateOIDCConfigWithSecret(ctx context.Context, arg UpdateOIDCConfigWithSecretParams) (*IdpOidcConfig, error) {
	row := q.db.QueryRow(ctx, updateOIDCConfigWithSecret,
		arg.ID,
		arg.Name,
		arg.Issuer,
		arg.ClientID,
		arg.ClientSecretEncrypted,
		arg.Scopes,
		arg.RequireEmailVerifiedClaim,
		arg.Enabled,
	)
	var i IdpOidcConfig
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Issuer,
		&i.ClientID,
		&i.ClientSecretEncrypted,
		&i.Scopes,
		&i.RequireEmailVerifiedClaim,
		&i.Enabled,
	)
	return &i, err
}
