// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: local_signup_verifications.sql

package storage

import (
	"context"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

const createLocalSignupVerification = `-- name: CreateLocalSignupVerification :one
INSERT INTO local_signup_verifications (email, password_hash, token_hash, expires_at)
VALUES ($1, $2, $3, $4)
RETURNING id
`

type CreateLocalSignupVerificationParams struct {
	Email        string             `json:"email"`
	PasswordHash string             `json:"password_hash"`
	TokenHash    string             `json:"token_hash"`
	ExpiresAt    pgtype.Timestamptz `json:"expires_at"`
}

func (q *Queries) CreateLocalSignupVerification(ctx context.Context, arg CreateLocalSignupVerificationParams) (uuid.UUID, error) {
	row := q.db.QueryRow(ctx, createLocalSignupVerification,
		arg.Email,
		arg.PasswordHash,
		arg.TokenHash,
		arg.ExpiresAt,
	)
	var id uuid.UUID
	err := row.Scan(&id)
	return id, err
}

const deleteLocalSignupVerification = `-- name: DeleteLocalSignupVerification :exec
DELETE FROM local_signup_verifications
WHERE id = $1
`

func (q *Queries) DeleteLocalSignupVerification(ctx context.Context, id uuid.UUID) error {
	_, err := q.db.Exec(ctx, deleteLocalSignupVerification, id)
	return err
}

const findLocalSignupVerificationByTokenHash = `-- name: FindLocalSignupVerificationByTokenHash :one
SELECT id, email, password_hash, expires_at
FROM local_signup_verifications
WHERE token_hash = $1
`

type FindLocalSignupVerificationByTokenHashRow struct {
	ID           uuid.UUID          `json:"id"`
	Email        string             `json:"email"`
	PasswordHash string             `json:"password_hash"`
	ExpiresAt    pgtype.Timestamptz `json:"expires_at"`
}

func (q *Queries) FindLocalSignupVerificationByTokenHash(ctx context.Context, tokenHash string) (*FindLocalSignupVerificationByTokenHashRow, error) {
	row := q.db.QueryRow(ctx, findLocalSignupVerificationByTokenHash, tokenHash)
	var i FindLocalSignupVerificationByTokenHashRow
	err := row.Scan(
		&i.ID,
		&i.Email,
		&i.PasswordHash,
		&i.ExpiresAt,
	)
	return &i, err
}
