// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: local_credentials.sql

package storage

import (
	"context"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

const findLocalCredential = `-- name: FindLocalCredential :one
SELECT user_id, password_hash, failed_attempts, locked_until
FROM local_credentials
WHERE user_id = $1
`

func (q *Queries) FindLocalCredential(ctx context.Context, userID uuid.UUID) (*LocalCredential, error) {
	row := q.db.QueryRow(ctx, findLocalCredential, userID)
	var i LocalCredential
	err := row.Scan(
		&i.UserID,
		&i.PasswordHash,
		&i.FailedAttempts,
		&i.LockedUntil,
	)
	return &i, err
}

const recordFailedLoginAttempt = `-- name: RecordFailedLoginAttempt :exec
UPDATE local_credentials
SET failed_attempts = $2, locked_until = $3
WHERE user_id = $1
`

type RecordFailedLoginAttemptParams struct {
	UserID         uuid.UUID          `json:"user_id"`
	FailedAttempts int32              `json:"failed_attempts"`
	LockedUntil    pgtype.Timestamptz `json:"locked_until"`
}

func (q *Queries) RecordFailedLoginAttempt(ctx context.Context, arg RecordFailedLoginAttemptParams) error {
	_, err := q.db.Exec(ctx, recordFailedLoginAttempt, arg.UserID, arg.FailedAttempts, arg.LockedUntil)
	return err
}

const resetFailedLoginAttempts = `-- name: ResetFailedLoginAttempts :exec
UPDATE local_credentials
SET failed_attempts = 0, locked_until = NULL
WHERE user_id = $1
`

func (q *Queries) ResetFailedLoginAttempts(ctx context.Context, userID uuid.UUID) error {
	_, err := q.db.Exec(ctx, resetFailedLoginAttempts, userID)
	return err
}

const upsertLocalCredentialPassword = `-- name: UpsertLocalCredentialPassword :exec
INSERT INTO local_credentials (user_id, password_hash, failed_attempts, locked_until)
VALUES ($1, $2, 0, NULL)
ON CONFLICT (user_id) DO UPDATE
SET password_hash = EXCLUDED.password_hash, failed_attempts = 0, locked_until = NULL
`

type UpsertLocalCredentialPasswordParams struct {
	UserID       uuid.UUID   `json:"user_id"`
	PasswordHash pgtype.Text `json:"password_hash"`
}

func (q *Queries) UpsertLocalCredentialPassword(ctx context.Context, arg UpsertLocalCredentialPasswordParams) error {
	_, err := q.db.Exec(ctx, upsertLocalCredentialPassword, arg.UserID, arg.PasswordHash)
	return err
}
