// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: migration.sql

package storage

import (
	"context"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

const insertMigratedShortURL = `-- name: InsertMigratedShortURL :one
INSERT INTO short_urls (domain_id, short_code, long_url, title, created_by, status, source, created_at)
VALUES ($1, $2, $3, $4, $5, 'active', 'yourls_import', $6)
RETURNING id
`

type InsertMigratedShortURLParams struct {
	DomainID  uuid.UUID          `json:"domain_id"`
	ShortCode string             `json:"short_code"`
	LongUrl   string             `json:"long_url"`
	Title     pgtype.Text        `json:"title"`
	CreatedBy uuid.UUID          `json:"created_by"`
	CreatedAt pgtype.Timestamptz `json:"created_at"`
}

// cmd/migrate-yourls専用(10節)。status/sourceは移行データに常に固定の値
// ('active'/'yourls_import')のためリテラルで埋め込み、created_atは
// YOURLS側のtimestampをそのまま引き継ぐ(通常のInsertShortURLはnow()任せ)。
func (q *Queries) InsertMigratedShortURL(ctx context.Context, arg InsertMigratedShortURLParams) (uuid.UUID, error) {
	row := q.db.QueryRow(ctx, insertMigratedShortURL,
		arg.DomainID,
		arg.ShortCode,
		arg.LongUrl,
		arg.Title,
		arg.CreatedBy,
		arg.CreatedAt,
	)
	var id uuid.UUID
	err := row.Scan(&id)
	return id, err
}

const setMigratedClickStatsDaily = `-- name: SetMigratedClickStatsDaily :exec
INSERT INTO click_stats_daily (short_url_id, date, click_count)
VALUES ($1, $2, $3)
ON CONFLICT (short_url_id, date) DO UPDATE SET click_count = EXCLUDED.click_count
`

type SetMigratedClickStatsDailyParams struct {
	ShortUrlID uuid.UUID   `json:"short_url_id"`
	Date       pgtype.Date `json:"date"`
	ClickCount int64       `json:"click_count"`
}

// 通常の運用中の集計(UpsertClickStatsDaily)は既存値に加算するが、移行は
// 「移行時点までの累計値を1レコードとして投入する」(10節)ため、
// 加算ではなく上書きする。再実行時に同じ日付・同じ値で入れ直しても
// 安全(冪等)。
func (q *Queries) SetMigratedClickStatsDaily(ctx context.Context, arg SetMigratedClickStatsDailyParams) error {
	_, err := q.db.Exec(ctx, setMigratedClickStatsDaily, arg.ShortUrlID, arg.Date, arg.ClickCount)
	return err
}
