// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package storage

import (
	"database/sql/driver"
	"fmt"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

type AuthProviderType string

const (
	AuthProviderTypeLocal AuthProviderType = "local"
	AuthProviderTypeSaml  AuthProviderType = "saml"
	AuthProviderTypeOidc  AuthProviderType = "oidc"
)

func (e *AuthProviderType) Scan(src interface{}) error {
	switch s := src.(type) {
	case []byte:
		*e = AuthProviderType(s)
	case string:
		*e = AuthProviderType(s)
	default:
		return fmt.Errorf("unsupported scan type for AuthProviderType: %T", src)
	}
	return nil
}

type NullAuthProviderType struct {
	AuthProviderType AuthProviderType `json:"auth_provider_type"`
	Valid            bool             `json:"valid"` // Valid is true if AuthProviderType is not NULL
}

// Scan implements the Scanner interface.
func (ns *NullAuthProviderType) Scan(value interface{}) error {
	if value == nil {
		ns.AuthProviderType, ns.Valid = "", false
		return nil
	}
	ns.Valid = true
	return ns.AuthProviderType.Scan(value)
}

// Value implements the driver Valuer interface.
func (ns NullAuthProviderType) Value() (driver.Value, error) {
	if !ns.Valid {
		return nil, nil
	}
	return string(ns.AuthProviderType), nil
}

type ShortUrlSource string

const (
	ShortUrlSourceNative       ShortUrlSource = "native"
	ShortUrlSourceYourlsImport ShortUrlSource = "yourls_import"
)

func (e *ShortUrlSource) Scan(src interface{}) error {
	switch s := src.(type) {
	case []byte:
		*e = ShortUrlSource(s)
	case string:
		*e = ShortUrlSource(s)
	default:
		return fmt.Errorf("unsupported scan type for ShortUrlSource: %T", src)
	}
	return nil
}

type NullShortUrlSource struct {
	ShortUrlSource ShortUrlSource `json:"short_url_source"`
	Valid          bool           `json:"valid"` // Valid is true if ShortUrlSource is not NULL
}

// Scan implements the Scanner interface.
func (ns *NullShortUrlSource) Scan(value interface{}) error {
	if value == nil {
		ns.ShortUrlSource, ns.Valid = "", false
		return nil
	}
	ns.Valid = true
	return ns.ShortUrlSource.Scan(value)
}

// Value implements the driver Valuer interface.
func (ns NullShortUrlSource) Value() (driver.Value, error) {
	if !ns.Valid {
		return nil, nil
	}
	return string(ns.ShortUrlSource), nil
}

type ShortUrlStatus string

const (
	ShortUrlStatusActive   ShortUrlStatus = "active"
	ShortUrlStatusDisabled ShortUrlStatus = "disabled"
	ShortUrlStatusExpired  ShortUrlStatus = "expired"
)

func (e *ShortUrlStatus) Scan(src interface{}) error {
	switch s := src.(type) {
	case []byte:
		*e = ShortUrlStatus(s)
	case string:
		*e = ShortUrlStatus(s)
	default:
		return fmt.Errorf("unsupported scan type for ShortUrlStatus: %T", src)
	}
	return nil
}

type NullShortUrlStatus struct {
	ShortUrlStatus ShortUrlStatus `json:"short_url_status"`
	Valid          bool           `json:"valid"` // Valid is true if ShortUrlStatus is not NULL
}

// Scan implements the Scanner interface.
func (ns *NullShortUrlStatus) Scan(value interface{}) error {
	if value == nil {
		ns.ShortUrlStatus, ns.Valid = "", false
		return nil
	}
	ns.Valid = true
	return ns.ShortUrlStatus.Scan(value)
}

// Value implements the driver Valuer interface.
func (ns NullShortUrlStatus) Value() (driver.Value, error) {
	if !ns.Valid {
		return nil, nil
	}
	return string(ns.ShortUrlStatus), nil
}

type UrlPermissionRole string

const (
	UrlPermissionRoleOwner  UrlPermissionRole = "owner"
	UrlPermissionRoleEditor UrlPermissionRole = "editor"
	UrlPermissionRoleViewer UrlPermissionRole = "viewer"
)

func (e *UrlPermissionRole) Scan(src interface{}) error {
	switch s := src.(type) {
	case []byte:
		*e = UrlPermissionRole(s)
	case string:
		*e = UrlPermissionRole(s)
	default:
		return fmt.Errorf("unsupported scan type for UrlPermissionRole: %T", src)
	}
	return nil
}

type NullUrlPermissionRole struct {
	UrlPermissionRole UrlPermissionRole `json:"url_permission_role"`
	Valid             bool              `json:"valid"` // Valid is true if UrlPermissionRole is not NULL
}

// Scan implements the Scanner interface.
func (ns *NullUrlPermissionRole) Scan(value interface{}) error {
	if value == nil {
		ns.UrlPermissionRole, ns.Valid = "", false
		return nil
	}
	ns.Valid = true
	return ns.UrlPermissionRole.Scan(value)
}

// Value implements the driver Valuer interface.
func (ns NullUrlPermissionRole) Value() (driver.Value, error) {
	if !ns.Valid {
		return nil, nil
	}
	return string(ns.UrlPermissionRole), nil
}

type UserStatus string

const (
	UserStatusActive    UserStatus = "active"
	UserStatusSuspended UserStatus = "suspended"
)

func (e *UserStatus) Scan(src interface{}) error {
	switch s := src.(type) {
	case []byte:
		*e = UserStatus(s)
	case string:
		*e = UserStatus(s)
	default:
		return fmt.Errorf("unsupported scan type for UserStatus: %T", src)
	}
	return nil
}

type NullUserStatus struct {
	UserStatus UserStatus `json:"user_status"`
	Valid      bool       `json:"valid"` // Valid is true if UserStatus is not NULL
}

// Scan implements the Scanner interface.
func (ns *NullUserStatus) Scan(value interface{}) error {
	if value == nil {
		ns.UserStatus, ns.Valid = "", false
		return nil
	}
	ns.Valid = true
	return ns.UserStatus.Scan(value)
}

// Value implements the driver Valuer interface.
func (ns NullUserStatus) Value() (driver.Value, error) {
	if !ns.Valid {
		return nil, nil
	}
	return string(ns.UserStatus), nil
}

type AuditLog struct {
	ID          uuid.UUID          `json:"id"`
	ActorUserID uuid.NullUUID      `json:"actor_user_id"`
	Action      string             `json:"action"`
	TargetType  pgtype.Text        `json:"target_type"`
	TargetID    pgtype.Text        `json:"target_id"`
	Metadata    []byte             `json:"metadata"`
	CreatedAt   pgtype.Timestamptz `json:"created_at"`
}

type AuthIdentity struct {
	ID               uuid.UUID          `json:"id"`
	UserID           uuid.UUID          `json:"user_id"`
	ProviderType     AuthProviderType   `json:"provider_type"`
	ProviderConfigID uuid.NullUUID      `json:"provider_config_id"`
	Subject          string             `json:"subject"`
	EmailAtLink      string             `json:"email_at_link"`
	Verified         bool               `json:"verified"`
	CreatedAt        pgtype.Timestamptz `json:"created_at"`
	LastUsedAt       pgtype.Timestamptz `json:"last_used_at"`
}

type AuthSetting struct {
	ID                                bool `json:"id"`
	LocalAuthEnabled                  bool `json:"local_auth_enabled"`
	SelfSignupEnabled                 bool `json:"self_signup_enabled"`
	RequireEmailConfirmationForSignup bool `json:"require_email_confirmation_for_signup"`
	RequireReauthForAccountLink       bool `json:"require_reauth_for_account_link"`
}

type ClickEvent struct {
	ID           int64              `json:"id"`
	ShortUrlID   uuid.UUID          `json:"short_url_id"`
	ClickedAt    pgtype.Timestamptz `json:"clicked_at"`
	ReferrerHost pgtype.Text        `json:"referrer_host"`
	UserAgentRaw pgtype.Text        `json:"user_agent_raw"`
	IpHash       pgtype.Text        `json:"ip_hash"`
	CountryCode  pgtype.Text        `json:"country_code"`
	StreamID     string             `json:"stream_id"`
	Os           pgtype.Text        `json:"os"`
	Browser      pgtype.Text        `json:"browser"`
}

type ClickEventsDefault struct {
	ID           int64              `json:"id"`
	ShortUrlID   uuid.UUID          `json:"short_url_id"`
	ClickedAt    pgtype.Timestamptz `json:"clicked_at"`
	ReferrerHost pgtype.Text        `json:"referrer_host"`
	UserAgentRaw pgtype.Text        `json:"user_agent_raw"`
	IpHash       pgtype.Text        `json:"ip_hash"`
	CountryCode  pgtype.Text        `json:"country_code"`
}

type ClickStatsDaily struct {
	ShortUrlID uuid.UUID   `json:"short_url_id"`
	Date       pgtype.Date `json:"date"`
	ClickCount int64       `json:"click_count"`
}

type Domain struct {
	ID        uuid.UUID `json:"id"`
	Hostname  string    `json:"hostname"`
	IsDefault bool      `json:"is_default"`
}

type IdpOidcConfig struct {
	ID                        uuid.UUID `json:"id"`
	Name                      string    `json:"name"`
	Issuer                    string    `json:"issuer"`
	ClientID                  string    `json:"client_id"`
	ClientSecretEncrypted     string    `json:"client_secret_encrypted"`
	Scopes                    []string  `json:"scopes"`
	RequireEmailVerifiedClaim bool      `json:"require_email_verified_claim"`
	Enabled                   bool      `json:"enabled"`
}

type IdpSamlConfig struct {
	ID             uuid.UUID `json:"id"`
	Name           string    `json:"name"`
	IdpEntityID    string    `json:"idp_entity_id"`
	IdpSsoUrl      string    `json:"idp_sso_url"`
	IdpCertificate string    `json:"idp_certificate"`
	EmailAttribute string    `json:"email_attribute"`
	Trusted        bool      `json:"trusted"`
	Enabled        bool      `json:"enabled"`
}

type LocalCredential struct {
	UserID         uuid.UUID          `json:"user_id"`
	PasswordHash   pgtype.Text        `json:"password_hash"`
	FailedAttempts int32              `json:"failed_attempts"`
	LockedUntil    pgtype.Timestamptz `json:"locked_until"`
}

type LocalSignupVerification struct {
	ID           uuid.UUID          `json:"id"`
	Email        string             `json:"email"`
	PasswordHash string             `json:"password_hash"`
	TokenHash    string             `json:"token_hash"`
	ExpiresAt    pgtype.Timestamptz `json:"expires_at"`
	CreatedAt    pgtype.Timestamptz `json:"created_at"`
}

type PendingLinkRequest struct {
	ID                        uuid.UUID          `json:"id"`
	ExistingUserID            uuid.UUID          `json:"existing_user_id"`
	CandidateProviderType     AuthProviderType   `json:"candidate_provider_type"`
	CandidateProviderConfigID uuid.NullUUID      `json:"candidate_provider_config_id"`
	CandidateSubject          string             `json:"candidate_subject"`
	TokenHash                 string             `json:"token_hash"`
	ExpiresAt                 pgtype.Timestamptz `json:"expires_at"`
	ConfirmedAt               pgtype.Timestamptz `json:"confirmed_at"`
}

type Session struct {
	ID         string             `json:"id"`
	UserID     uuid.UUID          `json:"user_id"`
	CreatedAt  pgtype.Timestamptz `json:"created_at"`
	ExpiresAt  pgtype.Timestamptz `json:"expires_at"`
	LastSeenAt pgtype.Timestamptz `json:"last_seen_at"`
}

type ShortCodeSetting struct {
	ID        bool               `json:"id"`
	Charset   string             `json:"charset"`
	Length    int32              `json:"length"`
	UpdatedAt pgtype.Timestamptz `json:"updated_at"`
}

type ShortUrl struct {
	ID          uuid.UUID          `json:"id"`
	DomainID    uuid.UUID          `json:"domain_id"`
	ShortCode   string             `json:"short_code"`
	LongUrl     string             `json:"long_url"`
	Title       pgtype.Text        `json:"title"`
	Description pgtype.Text        `json:"description"`
	CreatedBy   uuid.UUID          `json:"created_by"`
	Status      ShortUrlStatus     `json:"status"`
	ExpiresAt   pgtype.Timestamptz `json:"expires_at"`
	Source      ShortUrlSource     `json:"source"`
	CreatedAt   pgtype.Timestamptz `json:"created_at"`
	UpdatedAt   pgtype.Timestamptz `json:"updated_at"`
}

type UrlPermission struct {
	ID         uuid.UUID          `json:"id"`
	ShortUrlID uuid.UUID          `json:"short_url_id"`
	UserID     uuid.UUID          `json:"user_id"`
	Role       UrlPermissionRole  `json:"role"`
	GrantedBy  uuid.UUID          `json:"granted_by"`
	GrantedAt  pgtype.Timestamptz `json:"granted_at"`
}

type User struct {
	ID            uuid.UUID          `json:"id"`
	Email         string             `json:"email"`
	EmailVerified bool               `json:"email_verified"`
	DisplayName   pgtype.Text        `json:"display_name"`
	IsSystemAdmin bool               `json:"is_system_admin"`
	Status        UserStatus         `json:"status"`
	CreatedAt     pgtype.Timestamptz `json:"created_at"`
	UpdatedAt     pgtype.Timestamptz `json:"updated_at"`
}

type WebauthnCredential struct {
	ID             uuid.UUID          `json:"id"`
	UserID         uuid.UUID          `json:"user_id"`
	CredentialID   []byte             `json:"credential_id"`
	PublicKey      []byte             `json:"public_key"`
	SignCount      int64              `json:"sign_count"`
	Transports     []string           `json:"transports"`
	Name           pgtype.Text        `json:"name"`
	CreatedAt      pgtype.Timestamptz `json:"created_at"`
	LastUsedAt     pgtype.Timestamptz `json:"last_used_at"`
	UserPresent    bool               `json:"user_present"`
	UserVerified   bool               `json:"user_verified"`
	BackupEligible bool               `json:"backup_eligible"`
	BackupState    bool               `json:"backup_state"`
}
