// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: pending_link_requests.sql

package storage

import (
	"context"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

const confirmPendingLinkRequest = `-- name: ConfirmPendingLinkRequest :exec
UPDATE pending_link_requests
SET confirmed_at = $2
WHERE id = $1
`

type ConfirmPendingLinkRequestParams struct {
	ID          uuid.UUID          `json:"id"`
	ConfirmedAt pgtype.Timestamptz `json:"confirmed_at"`
}

func (q *Queries) ConfirmPendingLinkRequest(ctx context.Context, arg ConfirmPendingLinkRequestParams) error {
	_, err := q.db.Exec(ctx, confirmPendingLinkRequest, arg.ID, arg.ConfirmedAt)
	return err
}

const createPendingLinkRequest = `-- name: CreatePendingLinkRequest :one
INSERT INTO pending_link_requests (
    existing_user_id, candidate_provider_type, candidate_provider_config_id, candidate_subject, token_hash, expires_at
)
VALUES ($1, $2, $3, $4, $5, $6)
RETURNING id
`

type CreatePendingLinkRequestParams struct {
	ExistingUserID            uuid.UUID          `json:"existing_user_id"`
	CandidateProviderType     AuthProviderType   `json:"candidate_provider_type"`
	CandidateProviderConfigID uuid.NullUUID      `json:"candidate_provider_config_id"`
	CandidateSubject          string             `json:"candidate_subject"`
	TokenHash                 string             `json:"token_hash"`
	ExpiresAt                 pgtype.Timestamptz `json:"expires_at"`
}

func (q *Queries) CreatePendingLinkRequest(ctx context.Context, arg CreatePendingLinkRequestParams) (uuid.UUID, error) {
	row := q.db.QueryRow(ctx, createPendingLinkRequest,
		arg.ExistingUserID,
		arg.CandidateProviderType,
		arg.CandidateProviderConfigID,
		arg.CandidateSubject,
		arg.TokenHash,
		arg.ExpiresAt,
	)
	var id uuid.UUID
	err := row.Scan(&id)
	return id, err
}

const findPendingLinkRequestByTokenHash = `-- name: FindPendingLinkRequestByTokenHash :one
SELECT id, existing_user_id, candidate_provider_type, candidate_provider_config_id, candidate_subject, expires_at, confirmed_at
FROM pending_link_requests
WHERE token_hash = $1
`

type FindPendingLinkRequestByTokenHashRow struct {
	ID                        uuid.UUID          `json:"id"`
	ExistingUserID            uuid.UUID          `json:"existing_user_id"`
	CandidateProviderType     AuthProviderType   `json:"candidate_provider_type"`
	CandidateProviderConfigID uuid.NullUUID      `json:"candidate_provider_config_id"`
	CandidateSubject          string             `json:"candidate_subject"`
	ExpiresAt                 pgtype.Timestamptz `json:"expires_at"`
	ConfirmedAt               pgtype.Timestamptz `json:"confirmed_at"`
}

func (q *Queries) FindPendingLinkRequestByTokenHash(ctx context.Context, tokenHash string) (*FindPendingLinkRequestByTokenHashRow, error) {
	row := q.db.QueryRow(ctx, findPendingLinkRequestByTokenHash, tokenHash)
	var i FindPendingLinkRequestByTokenHashRow
	err := row.Scan(
		&i.ID,
		&i.ExistingUserID,
		&i.CandidateProviderType,
		&i.CandidateProviderConfigID,
		&i.CandidateSubject,
		&i.ExpiresAt,
		&i.ConfirmedAt,
	)
	return &i, err
}
