// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package storage

import (
	"context"

	"github.com/google/uuid"
)

type Querier interface {
	ConfirmPendingLinkRequest(ctx context.Context, arg ConfirmPendingLinkRequestParams) error
	CountAuthIdentitiesForUser(ctx context.Context, userID uuid.UUID) (int64, error)
	CreateAuthIdentity(ctx context.Context, arg CreateAuthIdentityParams) (*CreateAuthIdentityRow, error)
	CreatePendingLinkRequest(ctx context.Context, arg CreatePendingLinkRequestParams) (uuid.UUID, error)
	CreateUser(ctx context.Context, arg CreateUserParams) (*CreateUserRow, error)
	FindAuthIdentity(ctx context.Context, arg FindAuthIdentityParams) (*FindAuthIdentityRow, error)
	FindDefaultDomain(ctx context.Context) (uuid.UUID, error)
	FindPendingLinkRequestByTokenHash(ctx context.Context, tokenHash string) (*FindPendingLinkRequestByTokenHashRow, error)
	FindRedirectTarget(ctx context.Context, arg FindRedirectTargetParams) (*FindRedirectTargetRow, error)
	FindURLPermission(ctx context.Context, arg FindURLPermissionParams) (UrlPermissionRole, error)
	FindUserByEmail(ctx context.Context, email string) (*FindUserByEmailRow, error)
	FindUserByID(ctx context.Context, id uuid.UUID) (*FindUserByIDRow, error)
	RecordAuditLog(ctx context.Context, arg RecordAuditLogParams) error
	TouchAuthIdentity(ctx context.Context, arg TouchAuthIdentityParams) error
}

var _ Querier = (*Queries)(nil)
