// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package storage

import (
	"context"

	"github.com/google/uuid"
)

type Querier interface {
	ConfirmPendingLinkRequest(ctx context.Context, arg ConfirmPendingLinkRequestParams) error
	CountAuthIdentitiesForOIDCConfig(ctx context.Context, providerConfigID uuid.NullUUID) (int64, error)
	CountAuthIdentitiesForSAMLConfig(ctx context.Context, providerConfigID uuid.NullUUID) (int64, error)
	CountAuthIdentitiesForUser(ctx context.Context, userID uuid.UUID) (int64, error)
	CountURLOwners(ctx context.Context, shortUrlID uuid.UUID) (int64, error)
	CreateAuthIdentity(ctx context.Context, arg CreateAuthIdentityParams) (*CreateAuthIdentityRow, error)
	CreateLocalSignupVerification(ctx context.Context, arg CreateLocalSignupVerificationParams) (uuid.UUID, error)
	CreateOIDCConfig(ctx context.Context, arg CreateOIDCConfigParams) (*IdpOidcConfig, error)
	CreatePendingLinkRequest(ctx context.Context, arg CreatePendingLinkRequestParams) (uuid.UUID, error)
	CreateSAMLConfig(ctx context.Context, arg CreateSAMLConfigParams) (*IdpSamlConfig, error)
	CreateUser(ctx context.Context, arg CreateUserParams) (*CreateUserRow, error)
	DeleteLocalSignupVerification(ctx context.Context, id uuid.UUID) error
	DeleteOIDCConfig(ctx context.Context, id uuid.UUID) (int64, error)
	DeleteSAMLConfig(ctx context.Context, id uuid.UUID) (int64, error)
	DeleteURLPermission(ctx context.Context, arg DeleteURLPermissionParams) error
	FindAdminUserByID(ctx context.Context, id uuid.UUID) (*FindAdminUserByIDRow, error)
	FindAuthIdentity(ctx context.Context, arg FindAuthIdentityParams) (*FindAuthIdentityRow, error)
	FindAuthSettings(ctx context.Context) (*FindAuthSettingsRow, error)
	FindDailyClickCounts(ctx context.Context, arg FindDailyClickCountsParams) ([]*FindDailyClickCountsRow, error)
	FindDefaultDomain(ctx context.Context) (uuid.UUID, error)
	FindIsSystemAdmin(ctx context.Context, id uuid.UUID) (bool, error)
	FindLocalCredential(ctx context.Context, userID uuid.UUID) (*LocalCredential, error)
	FindLocalSignupVerificationByTokenHash(ctx context.Context, tokenHash string) (*FindLocalSignupVerificationByTokenHashRow, error)
	FindOIDCConfigByID(ctx context.Context, id uuid.UUID) (*IdpOidcConfig, error)
	FindPendingLinkRequestByID(ctx context.Context, id uuid.UUID) (*FindPendingLinkRequestByIDRow, error)
	FindPendingLinkRequestByTokenHash(ctx context.Context, tokenHash string) (*FindPendingLinkRequestByTokenHashRow, error)
	FindPendingLinkRequestsForUser(ctx context.Context, existingUserID uuid.UUID) ([]*FindPendingLinkRequestsForUserRow, error)
	FindRedirectTarget(ctx context.Context, arg FindRedirectTargetParams) (*FindRedirectTargetRow, error)
	FindReferrerClickCounts(ctx context.Context, arg FindReferrerClickCountsParams) ([]*FindReferrerClickCountsRow, error)
	FindSAMLConfigByID(ctx context.Context, id uuid.UUID) (*IdpSamlConfig, error)
	FindShortCodeSettings(ctx context.Context) (*FindShortCodeSettingsRow, error)
	FindShortURLByID(ctx context.Context, id uuid.UUID) (*ShortUrl, error)
	FindURLPermission(ctx context.Context, arg FindURLPermissionParams) (UrlPermissionRole, error)
	FindUserByEmail(ctx context.Context, email string) (*FindUserByEmailRow, error)
	FindUserByID(ctx context.Context, id uuid.UUID) (*FindUserByIDRow, error)
	InsertClickEvent(ctx context.Context, arg InsertClickEventParams) (int64, error)
	InsertShortURL(ctx context.Context, arg InsertShortURLParams) (*InsertShortURLRow, error)
	InsertURLPermission(ctx context.Context, arg InsertURLPermissionParams) error
	ListOIDCConfigs(ctx context.Context) ([]*IdpOidcConfig, error)
	ListSAMLConfigs(ctx context.Context) ([]*IdpSamlConfig, error)
	ListURLPermissions(ctx context.Context, shortUrlID uuid.UUID) ([]*ListURLPermissionsRow, error)
	ListUsers(ctx context.Context, arg ListUsersParams) ([]*ListUsersRow, error)
	RecordAuditLog(ctx context.Context, arg RecordAuditLogParams) error
	RecordFailedLoginAttempt(ctx context.Context, arg RecordFailedLoginAttemptParams) error
	ResetFailedLoginAttempts(ctx context.Context, userID uuid.UUID) error
	SetShortURLStatus(ctx context.Context, arg SetShortURLStatusParams) error
	SetSystemAdmin(ctx context.Context, arg SetSystemAdminParams) (int64, error)
	SetUserStatus(ctx context.Context, arg SetUserStatusParams) (int64, error)
	TouchAuthIdentity(ctx context.Context, arg TouchAuthIdentityParams) error
	UpdateAuthSettings(ctx context.Context, arg UpdateAuthSettingsParams) error
	UpdateOIDCConfig(ctx context.Context, arg UpdateOIDCConfigParams) (*IdpOidcConfig, error)
	UpdateOIDCConfigWithSecret(ctx context.Context, arg UpdateOIDCConfigWithSecretParams) (*IdpOidcConfig, error)
	UpdateSAMLConfig(ctx context.Context, arg UpdateSAMLConfigParams) (*IdpSamlConfig, error)
	// ListShortURLsForUser/ListAllShortURLs (filter+sort+pagination+total count,
	// 4.1節) are hand-written in shorturl_store.go instead of here: sqlc can't
	// parameterize a dynamic ORDER BY column, which this listing needs to let
	// every displayed field be sortable.
	UpdateShortURLFields(ctx context.Context, arg UpdateShortURLFieldsParams) (*ShortUrl, error)
	UpsertClickStatsDaily(ctx context.Context, arg UpsertClickStatsDailyParams) error
	UpsertLocalCredentialPassword(ctx context.Context, arg UpsertLocalCredentialPasswordParams) error
	UpsertURLPermission(ctx context.Context, arg UpsertURLPermissionParams) error
}

var _ Querier = (*Queries)(nil)
