// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: short_code_settings.sql

package storage

import (
	"context"
)

const findShortCodeSettings = `-- name: FindShortCodeSettings :one
SELECT charset, length
FROM short_code_settings
WHERE id
`

type FindShortCodeSettingsRow struct {
	Charset string `json:"charset"`
	Length  int32  `json:"length"`
}

func (q *Queries) FindShortCodeSettings(ctx context.Context) (*FindShortCodeSettingsRow, error) {
	row := q.db.QueryRow(ctx, findShortCodeSettings)
	var i FindShortCodeSettingsRow
	err := row.Scan(&i.Charset, &i.Length)
	return &i, err
}
