// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: short_urls.sql

package storage

import (
	"context"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

const findRedirectTarget = `-- name: FindRedirectTarget :one
SELECT id, long_url
FROM short_urls
WHERE domain_id = $1
  AND short_code = $2
  AND status = 'active'
  AND (expires_at IS NULL OR expires_at > now())
`

type FindRedirectTargetParams struct {
	DomainID  uuid.UUID `json:"domain_id"`
	ShortCode string    `json:"short_code"`
}

type FindRedirectTargetRow struct {
	ID      uuid.UUID `json:"id"`
	LongUrl string    `json:"long_url"`
}

func (q *Queries) FindRedirectTarget(ctx context.Context, arg FindRedirectTargetParams) (*FindRedirectTargetRow, error) {
	row := q.db.QueryRow(ctx, findRedirectTarget, arg.DomainID, arg.ShortCode)
	var i FindRedirectTargetRow
	err := row.Scan(&i.ID, &i.LongUrl)
	return &i, err
}

const findShortURLByID = `-- name: FindShortURLByID :one
SELECT id, domain_id, short_code, long_url, title, description, created_by, status, expires_at, source, created_at, updated_at
FROM short_urls
WHERE id = $1
`

func (q *Queries) FindShortURLByID(ctx context.Context, id uuid.UUID) (*ShortUrl, error) {
	row := q.db.QueryRow(ctx, findShortURLByID, id)
	var i ShortUrl
	err := row.Scan(
		&i.ID,
		&i.DomainID,
		&i.ShortCode,
		&i.LongUrl,
		&i.Title,
		&i.Description,
		&i.CreatedBy,
		&i.Status,
		&i.ExpiresAt,
		&i.Source,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return &i, err
}

const insertShortURL = `-- name: InsertShortURL :one
INSERT INTO short_urls (domain_id, short_code, long_url, title, description, created_by, status, expires_at, source)
VALUES ($1, $2, $3, $4, $5, $6, $7, $8, $9)
RETURNING id, created_at
`

type InsertShortURLParams struct {
	DomainID    uuid.UUID          `json:"domain_id"`
	ShortCode   string             `json:"short_code"`
	LongUrl     string             `json:"long_url"`
	Title       pgtype.Text        `json:"title"`
	Description pgtype.Text        `json:"description"`
	CreatedBy   uuid.UUID          `json:"created_by"`
	Status      ShortUrlStatus     `json:"status"`
	ExpiresAt   pgtype.Timestamptz `json:"expires_at"`
	Source      ShortUrlSource     `json:"source"`
}

type InsertShortURLRow struct {
	ID        uuid.UUID          `json:"id"`
	CreatedAt pgtype.Timestamptz `json:"created_at"`
}

func (q *Queries) InsertShortURL(ctx context.Context, arg InsertShortURLParams) (*InsertShortURLRow, error) {
	row := q.db.QueryRow(ctx, insertShortURL,
		arg.DomainID,
		arg.ShortCode,
		arg.LongUrl,
		arg.Title,
		arg.Description,
		arg.CreatedBy,
		arg.Status,
		arg.ExpiresAt,
		arg.Source,
	)
	var i InsertShortURLRow
	err := row.Scan(&i.ID, &i.CreatedAt)
	return &i, err
}

const setShortURLStatus = `-- name: SetShortURLStatus :exec
UPDATE short_urls
SET status = $2, updated_at = now()
WHERE id = $1
`

type SetShortURLStatusParams struct {
	ID     uuid.UUID      `json:"id"`
	Status ShortUrlStatus `json:"status"`
}

func (q *Queries) SetShortURLStatus(ctx context.Context, arg SetShortURLStatusParams) error {
	_, err := q.db.Exec(ctx, setShortURLStatus, arg.ID, arg.Status)
	return err
}

const updateShortURLFields = `-- name: UpdateShortURLFields :one

UPDATE short_urls
SET long_url = $2, title = $3, description = $4, expires_at = $5, updated_at = now()
WHERE id = $1
RETURNING id, domain_id, short_code, long_url, title, description, created_by, status, expires_at, source, created_at, updated_at
`

type UpdateShortURLFieldsParams struct {
	ID          uuid.UUID          `json:"id"`
	LongUrl     string             `json:"long_url"`
	Title       pgtype.Text        `json:"title"`
	Description pgtype.Text        `json:"description"`
	ExpiresAt   pgtype.Timestamptz `json:"expires_at"`
}

// ListShortURLsForUser/ListAllShortURLs (filter+sort+pagination+total count,
// 4.1節) are hand-written in shorturl_store.go instead of here: sqlc can't
// parameterize a dynamic ORDER BY column, which this listing needs to let
// every displayed field be sortable.
func (q *Queries) UpdateShortURLFields(ctx context.Context, arg UpdateShortURLFieldsParams) (*ShortUrl, error) {
	row := q.db.QueryRow(ctx, updateShortURLFields,
		arg.ID,
		arg.LongUrl,
		arg.Title,
		arg.Description,
		arg.ExpiresAt,
	)
	var i ShortUrl
	err := row.Scan(
		&i.ID,
		&i.DomainID,
		&i.ShortCode,
		&i.LongUrl,
		&i.Title,
		&i.Description,
		&i.CreatedBy,
		&i.Status,
		&i.ExpiresAt,
		&i.Source,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return &i, err
}
