// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: short_urls.sql

package storage

import (
	"context"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

const findRedirectTarget = `-- name: FindRedirectTarget :one
SELECT id, long_url
FROM short_urls
WHERE domain_id = $1
  AND short_code = $2
  AND status = 'active'
  AND (expires_at IS NULL OR expires_at > now())
`

type FindRedirectTargetParams struct {
	DomainID  uuid.UUID `json:"domain_id"`
	ShortCode string    `json:"short_code"`
}

type FindRedirectTargetRow struct {
	ID      uuid.UUID `json:"id"`
	LongUrl string    `json:"long_url"`
}

func (q *Queries) FindRedirectTarget(ctx context.Context, arg FindRedirectTargetParams) (*FindRedirectTargetRow, error) {
	row := q.db.QueryRow(ctx, findRedirectTarget, arg.DomainID, arg.ShortCode)
	var i FindRedirectTargetRow
	err := row.Scan(&i.ID, &i.LongUrl)
	return &i, err
}

const findShortURLByID = `-- name: FindShortURLByID :one
SELECT id, domain_id, short_code, long_url, title, description, created_by, status, expires_at, source, created_at, updated_at
FROM short_urls
WHERE id = $1
`

func (q *Queries) FindShortURLByID(ctx context.Context, id uuid.UUID) (*ShortUrl, error) {
	row := q.db.QueryRow(ctx, findShortURLByID, id)
	var i ShortUrl
	err := row.Scan(
		&i.ID,
		&i.DomainID,
		&i.ShortCode,
		&i.LongUrl,
		&i.Title,
		&i.Description,
		&i.CreatedBy,
		&i.Status,
		&i.ExpiresAt,
		&i.Source,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return &i, err
}

const insertShortURL = `-- name: InsertShortURL :one
INSERT INTO short_urls (domain_id, short_code, long_url, title, description, created_by, status, expires_at, source)
VALUES ($1, $2, $3, $4, $5, $6, $7, $8, $9)
RETURNING id
`

type InsertShortURLParams struct {
	DomainID    uuid.UUID          `json:"domain_id"`
	ShortCode   string             `json:"short_code"`
	LongUrl     string             `json:"long_url"`
	Title       pgtype.Text        `json:"title"`
	Description pgtype.Text        `json:"description"`
	CreatedBy   uuid.UUID          `json:"created_by"`
	Status      ShortUrlStatus     `json:"status"`
	ExpiresAt   pgtype.Timestamptz `json:"expires_at"`
	Source      ShortUrlSource     `json:"source"`
}

func (q *Queries) InsertShortURL(ctx context.Context, arg InsertShortURLParams) (uuid.UUID, error) {
	row := q.db.QueryRow(ctx, insertShortURL,
		arg.DomainID,
		arg.ShortCode,
		arg.LongUrl,
		arg.Title,
		arg.Description,
		arg.CreatedBy,
		arg.Status,
		arg.ExpiresAt,
		arg.Source,
	)
	var id uuid.UUID
	err := row.Scan(&id)
	return id, err
}
