// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: url_permissions.sql

package storage

import (
	"context"

	"github.com/google/uuid"
)

const findURLPermission = `-- name: FindURLPermission :one
SELECT role
FROM url_permissions
WHERE short_url_id = $1 AND user_id = $2
`

type FindURLPermissionParams struct {
	ShortUrlID uuid.UUID `json:"short_url_id"`
	UserID     uuid.UUID `json:"user_id"`
}

func (q *Queries) FindURLPermission(ctx context.Context, arg FindURLPermissionParams) (UrlPermissionRole, error) {
	row := q.db.QueryRow(ctx, findURLPermission, arg.ShortUrlID, arg.UserID)
	var role UrlPermissionRole
	err := row.Scan(&role)
	return role, err
}
