// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: users.sql

package storage

import (
	"context"

	"github.com/google/uuid"
)

const createUser = `-- name: CreateUser :one
INSERT INTO users (email, email_verified)
VALUES ($1, $2)
RETURNING id, email, email_verified
`

type CreateUserParams struct {
	Email         string `json:"email"`
	EmailVerified bool   `json:"email_verified"`
}

type CreateUserRow struct {
	ID            uuid.UUID `json:"id"`
	Email         string    `json:"email"`
	EmailVerified bool      `json:"email_verified"`
}

func (q *Queries) CreateUser(ctx context.Context, arg CreateUserParams) (*CreateUserRow, error) {
	row := q.db.QueryRow(ctx, createUser, arg.Email, arg.EmailVerified)
	var i CreateUserRow
	err := row.Scan(&i.ID, &i.Email, &i.EmailVerified)
	return &i, err
}

const findIsSystemAdmin = `-- name: FindIsSystemAdmin :one
SELECT is_system_admin
FROM users
WHERE id = $1
`

func (q *Queries) FindIsSystemAdmin(ctx context.Context, id uuid.UUID) (bool, error) {
	row := q.db.QueryRow(ctx, findIsSystemAdmin, id)
	var is_system_admin bool
	err := row.Scan(&is_system_admin)
	return is_system_admin, err
}

const findUserByEmail = `-- name: FindUserByEmail :one
SELECT id, email, email_verified
FROM users
WHERE email = $1
`

type FindUserByEmailRow struct {
	ID            uuid.UUID `json:"id"`
	Email         string    `json:"email"`
	EmailVerified bool      `json:"email_verified"`
}

func (q *Queries) FindUserByEmail(ctx context.Context, email string) (*FindUserByEmailRow, error) {
	row := q.db.QueryRow(ctx, findUserByEmail, email)
	var i FindUserByEmailRow
	err := row.Scan(&i.ID, &i.Email, &i.EmailVerified)
	return &i, err
}

const findUserByID = `-- name: FindUserByID :one
SELECT id, email, email_verified
FROM users
WHERE id = $1
`

type FindUserByIDRow struct {
	ID            uuid.UUID `json:"id"`
	Email         string    `json:"email"`
	EmailVerified bool      `json:"email_verified"`
}

func (q *Queries) FindUserByID(ctx context.Context, id uuid.UUID) (*FindUserByIDRow, error) {
	row := q.db.QueryRow(ctx, findUserByID, id)
	var i FindUserByIDRow
	err := row.Scan(&i.ID, &i.Email, &i.EmailVerified)
	return &i, err
}
