// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: users.sql

package storage

import (
	"context"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

const createUser = `-- name: CreateUser :one
INSERT INTO users (email, email_verified)
VALUES ($1, $2)
RETURNING id, email, email_verified
`

type CreateUserParams struct {
	Email         string `json:"email"`
	EmailVerified bool   `json:"email_verified"`
}

type CreateUserRow struct {
	ID            uuid.UUID `json:"id"`
	Email         string    `json:"email"`
	EmailVerified bool      `json:"email_verified"`
}

func (q *Queries) CreateUser(ctx context.Context, arg CreateUserParams) (*CreateUserRow, error) {
	row := q.db.QueryRow(ctx, createUser, arg.Email, arg.EmailVerified)
	var i CreateUserRow
	err := row.Scan(&i.ID, &i.Email, &i.EmailVerified)
	return &i, err
}

const findAdminUserByID = `-- name: FindAdminUserByID :one
SELECT id, email, email_verified, is_system_admin, status, created_at
FROM users
WHERE id = $1
`

type FindAdminUserByIDRow struct {
	ID            uuid.UUID          `json:"id"`
	Email         string             `json:"email"`
	EmailVerified bool               `json:"email_verified"`
	IsSystemAdmin bool               `json:"is_system_admin"`
	Status        UserStatus         `json:"status"`
	CreatedAt     pgtype.Timestamptz `json:"created_at"`
}

func (q *Queries) FindAdminUserByID(ctx context.Context, id uuid.UUID) (*FindAdminUserByIDRow, error) {
	row := q.db.QueryRow(ctx, findAdminUserByID, id)
	var i FindAdminUserByIDRow
	err := row.Scan(
		&i.ID,
		&i.Email,
		&i.EmailVerified,
		&i.IsSystemAdmin,
		&i.Status,
		&i.CreatedAt,
	)
	return &i, err
}

const findIsSystemAdmin = `-- name: FindIsSystemAdmin :one
SELECT is_system_admin
FROM users
WHERE id = $1
`

func (q *Queries) FindIsSystemAdmin(ctx context.Context, id uuid.UUID) (bool, error) {
	row := q.db.QueryRow(ctx, findIsSystemAdmin, id)
	var is_system_admin bool
	err := row.Scan(&is_system_admin)
	return is_system_admin, err
}

const findUserByEmail = `-- name: FindUserByEmail :one
SELECT id, email, email_verified
FROM users
WHERE email = $1
`

type FindUserByEmailRow struct {
	ID            uuid.UUID `json:"id"`
	Email         string    `json:"email"`
	EmailVerified bool      `json:"email_verified"`
}

func (q *Queries) FindUserByEmail(ctx context.Context, email string) (*FindUserByEmailRow, error) {
	row := q.db.QueryRow(ctx, findUserByEmail, email)
	var i FindUserByEmailRow
	err := row.Scan(&i.ID, &i.Email, &i.EmailVerified)
	return &i, err
}

const findUserByID = `-- name: FindUserByID :one
SELECT id, email, email_verified
FROM users
WHERE id = $1
`

type FindUserByIDRow struct {
	ID            uuid.UUID `json:"id"`
	Email         string    `json:"email"`
	EmailVerified bool      `json:"email_verified"`
}

func (q *Queries) FindUserByID(ctx context.Context, id uuid.UUID) (*FindUserByIDRow, error) {
	row := q.db.QueryRow(ctx, findUserByID, id)
	var i FindUserByIDRow
	err := row.Scan(&i.ID, &i.Email, &i.EmailVerified)
	return &i, err
}

const listUsers = `-- name: ListUsers :many
SELECT id, email, email_verified, is_system_admin, status, created_at
FROM users
ORDER BY created_at DESC
LIMIT $1 OFFSET $2
`

type ListUsersParams struct {
	Limit  int32 `json:"limit"`
	Offset int32 `json:"offset"`
}

type ListUsersRow struct {
	ID            uuid.UUID          `json:"id"`
	Email         string             `json:"email"`
	EmailVerified bool               `json:"email_verified"`
	IsSystemAdmin bool               `json:"is_system_admin"`
	Status        UserStatus         `json:"status"`
	CreatedAt     pgtype.Timestamptz `json:"created_at"`
}

func (q *Queries) ListUsers(ctx context.Context, arg ListUsersParams) ([]*ListUsersRow, error) {
	rows, err := q.db.Query(ctx, listUsers, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []*ListUsersRow
	for rows.Next() {
		var i ListUsersRow
		if err := rows.Scan(
			&i.ID,
			&i.Email,
			&i.EmailVerified,
			&i.IsSystemAdmin,
			&i.Status,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, &i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const setSystemAdmin = `-- name: SetSystemAdmin :execrows
UPDATE users
SET is_system_admin = $2, updated_at = now()
WHERE id = $1
`

type SetSystemAdminParams struct {
	ID            uuid.UUID `json:"id"`
	IsSystemAdmin bool      `json:"is_system_admin"`
}

func (q *Queries) SetSystemAdmin(ctx context.Context, arg SetSystemAdminParams) (int64, error) {
	result, err := q.db.Exec(ctx, setSystemAdmin, arg.ID, arg.IsSystemAdmin)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const setUserStatus = `-- name: SetUserStatus :execrows
UPDATE users
SET status = $2, updated_at = now()
WHERE id = $1
`

type SetUserStatusParams struct {
	ID     uuid.UUID  `json:"id"`
	Status UserStatus `json:"status"`
}

func (q *Queries) SetUserStatus(ctx context.Context, arg SetUserStatusParams) (int64, error) {
	result, err := q.db.Exec(ctx, setUserStatus, arg.ID, arg.Status)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}
