// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: webauthn_credentials.sql

package storage

import (
	"context"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

const deleteWebAuthnCredential = `-- name: DeleteWebAuthnCredential :execrows
DELETE FROM webauthn_credentials
WHERE id = $1 AND user_id = $2
`

type DeleteWebAuthnCredentialParams struct {
	ID     uuid.UUID `json:"id"`
	UserID uuid.UUID `json:"user_id"`
}

func (q *Queries) DeleteWebAuthnCredential(ctx context.Context, arg DeleteWebAuthnCredentialParams) (int64, error) {
	result, err := q.db.Exec(ctx, deleteWebAuthnCredential, arg.ID, arg.UserID)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const findWebAuthnCredentialsByUserID = `-- name: FindWebAuthnCredentialsByUserID :many
SELECT id, user_id, credential_id, public_key, sign_count, transports, name, created_at, last_used_at,
       user_present, user_verified, backup_eligible, backup_state
FROM webauthn_credentials
WHERE user_id = $1
ORDER BY created_at DESC
`

func (q *Queries) FindWebAuthnCredentialsByUserID(ctx context.Context, userID uuid.UUID) ([]*WebauthnCredential, error) {
	rows, err := q.db.Query(ctx, findWebAuthnCredentialsByUserID, userID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []*WebauthnCredential
	for rows.Next() {
		var i WebauthnCredential
		if err := rows.Scan(
			&i.ID,
			&i.UserID,
			&i.CredentialID,
			&i.PublicKey,
			&i.SignCount,
			&i.Transports,
			&i.Name,
			&i.CreatedAt,
			&i.LastUsedAt,
			&i.UserPresent,
			&i.UserVerified,
			&i.BackupEligible,
			&i.BackupState,
		); err != nil {
			return nil, err
		}
		items = append(items, &i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const insertWebAuthnCredential = `-- name: InsertWebAuthnCredential :exec
INSERT INTO webauthn_credentials (user_id, credential_id, public_key, sign_count, transports, name,
                                   user_present, user_verified, backup_eligible, backup_state)
VALUES ($1, $2, $3, $4, $5, $6, $7, $8, $9, $10)
`

type InsertWebAuthnCredentialParams struct {
	UserID         uuid.UUID   `json:"user_id"`
	CredentialID   []byte      `json:"credential_id"`
	PublicKey      []byte      `json:"public_key"`
	SignCount      int64       `json:"sign_count"`
	Transports     []string    `json:"transports"`
	Name           pgtype.Text `json:"name"`
	UserPresent    bool        `json:"user_present"`
	UserVerified   bool        `json:"user_verified"`
	BackupEligible bool        `json:"backup_eligible"`
	BackupState    bool        `json:"backup_state"`
}

func (q *Queries) InsertWebAuthnCredential(ctx context.Context, arg InsertWebAuthnCredentialParams) error {
	_, err := q.db.Exec(ctx, insertWebAuthnCredential,
		arg.UserID,
		arg.CredentialID,
		arg.PublicKey,
		arg.SignCount,
		arg.Transports,
		arg.Name,
		arg.UserPresent,
		arg.UserVerified,
		arg.BackupEligible,
		arg.BackupState,
	)
	return err
}

const updateWebAuthnCredentialName = `-- name: UpdateWebAuthnCredentialName :one
UPDATE webauthn_credentials
SET name = $3
WHERE id = $1 AND user_id = $2
RETURNING id, user_id, credential_id, public_key, sign_count, transports, name, created_at, last_used_at,
          user_present, user_verified, backup_eligible, backup_state
`

type UpdateWebAuthnCredentialNameParams struct {
	ID     uuid.UUID   `json:"id"`
	UserID uuid.UUID   `json:"user_id"`
	Name   pgtype.Text `json:"name"`
}

func (q *Queries) UpdateWebAuthnCredentialName(ctx context.Context, arg UpdateWebAuthnCredentialNameParams) (*WebauthnCredential, error) {
	row := q.db.QueryRow(ctx, updateWebAuthnCredentialName, arg.ID, arg.UserID, arg.Name)
	var i WebauthnCredential
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.CredentialID,
		&i.PublicKey,
		&i.SignCount,
		&i.Transports,
		&i.Name,
		&i.CreatedAt,
		&i.LastUsedAt,
		&i.UserPresent,
		&i.UserVerified,
		&i.BackupEligible,
		&i.BackupState,
	)
	return &i, err
}

const updateWebAuthnCredentialSignCount = `-- name: UpdateWebAuthnCredentialSignCount :exec
UPDATE webauthn_credentials
SET sign_count = $2, backup_state = $3, last_used_at = now()
WHERE credential_id = $1
`

type UpdateWebAuthnCredentialSignCountParams struct {
	CredentialID []byte `json:"credential_id"`
	SignCount    int64  `json:"sign_count"`
	BackupState  bool   `json:"backup_state"`
}

// ログイン成功のたびに呼ばれる(WebAuthnService.applyLoginResult)。
// go-webauthnのストレージ指針(webauthn/doc.go)により、sign_countと
// last_used_atに加えbackup_state(変化しうる値)も毎回書き戻す。
// backup_eligibleは登録時から変化しない値のためここでは更新しない。
func (q *Queries) UpdateWebAuthnCredentialSignCount(ctx context.Context, arg UpdateWebAuthnCredentialSignCountParams) error {
	_, err := q.db.Exec(ctx, updateWebAuthnCredentialSignCount, arg.CredentialID, arg.SignCount, arg.BackupState)
	return err
}
