// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: webauthn_credentials.sql

package storage

import (
	"context"

	"github.com/google/uuid"
)

const deleteWebAuthnCredential = `-- name: DeleteWebAuthnCredential :execrows
DELETE FROM webauthn_credentials
WHERE id = $1 AND user_id = $2
`

type DeleteWebAuthnCredentialParams struct {
	ID     uuid.UUID `json:"id"`
	UserID uuid.UUID `json:"user_id"`
}

func (q *Queries) DeleteWebAuthnCredential(ctx context.Context, arg DeleteWebAuthnCredentialParams) (int64, error) {
	result, err := q.db.Exec(ctx, deleteWebAuthnCredential, arg.ID, arg.UserID)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const findWebAuthnCredentialsByUserID = `-- name: FindWebAuthnCredentialsByUserID :many
SELECT id, user_id, credential_id, public_key, sign_count, transports
FROM webauthn_credentials
WHERE user_id = $1
ORDER BY id
`

func (q *Queries) FindWebAuthnCredentialsByUserID(ctx context.Context, userID uuid.UUID) ([]*WebauthnCredential, error) {
	rows, err := q.db.Query(ctx, findWebAuthnCredentialsByUserID, userID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []*WebauthnCredential
	for rows.Next() {
		var i WebauthnCredential
		if err := rows.Scan(
			&i.ID,
			&i.UserID,
			&i.CredentialID,
			&i.PublicKey,
			&i.SignCount,
			&i.Transports,
		); err != nil {
			return nil, err
		}
		items = append(items, &i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const insertWebAuthnCredential = `-- name: InsertWebAuthnCredential :exec
INSERT INTO webauthn_credentials (user_id, credential_id, public_key, sign_count, transports)
VALUES ($1, $2, $3, $4, $5)
`

type InsertWebAuthnCredentialParams struct {
	UserID       uuid.UUID `json:"user_id"`
	CredentialID []byte    `json:"credential_id"`
	PublicKey    []byte    `json:"public_key"`
	SignCount    int64     `json:"sign_count"`
	Transports   []string  `json:"transports"`
}

func (q *Queries) InsertWebAuthnCredential(ctx context.Context, arg InsertWebAuthnCredentialParams) error {
	_, err := q.db.Exec(ctx, insertWebAuthnCredential,
		arg.UserID,
		arg.CredentialID,
		arg.PublicKey,
		arg.SignCount,
		arg.Transports,
	)
	return err
}

const updateWebAuthnCredentialSignCount = `-- name: UpdateWebAuthnCredentialSignCount :exec
UPDATE webauthn_credentials
SET sign_count = $2
WHERE credential_id = $1
`

type UpdateWebAuthnCredentialSignCountParams struct {
	CredentialID []byte `json:"credential_id"`
	SignCount    int64  `json:"sign_count"`
}

func (q *Queries) UpdateWebAuthnCredentialSignCount(ctx context.Context, arg UpdateWebAuthnCredentialSignCountParams) error {
	_, err := q.db.Exec(ctx, updateWebAuthnCredentialSignCount, arg.CredentialID, arg.SignCount)
	return err
}
